// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Actor struct {
	ActorID    uint16    `db:"actor_id" json:"actor_id"`
	FirstName  string    `db:"first_name" json:"first_name"`
	LastName   string    `db:"last_name" json:"last_name"`
	LastUpdate time.Time `db:"last_update" json:"last_update"`
}

type City struct {
	CityID     uint16    `db:"city_id" json:"city_id"`
	City       string    `db:"city" json:"city"`
	CountryID  uint16    `db:"country_id" json:"country_id"`
	LastUpdate time.Time `db:"last_update" json:"last_update"`
}

type Country struct {
	CountryID  uint16    `db:"country_id" json:"country_id"`
	Country    string    `db:"country" json:"country"`
	LastUpdate time.Time `db:"last_update" json:"last_update"`
}
