// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Actor struct {
	ActorID    uint16    `db:"actor_id" json:"actor_id"`
	FirstName  string    `db:"first_name" json:"first_name"`
	LastName   string    `db:"last_name" json:"last_name"`
	LastUpdate time.Time `db:"last_update" json:"last_update"`
}

type City struct {
	CityID     uint16    `db:"city_id" json:"city_id"`
	City       string    `db:"city" json:"city"`
	CountryID  uint16    `db:"country_id" json:"country_id"`
	LastUpdate time.Time `db:"last_update" json:"last_update"`
}

type Country struct {
	CountryID  uint16    `db:"country_id" json:"country_id"`
	Country    string    `db:"country" json:"country"`
	LastUpdate time.Time `db:"last_update" json:"last_update"`
}

type User struct {
	UserID       uint32       `db:"user_id" json:"user_id"`
	Username     string       `db:"username" json:"username"`
	PasswordHash string       `db:"password_hash" json:"password_hash"`
	CreatedAt    sql.NullTime `db:"created_at" json:"created_at"`
}
